version: 2

models:
  - name: stg_github_repositories
    columns:
      - name: repository_id
        tests:
          - not_null
          - unique

      - name: repository_name
        tests:
          - not_null

  - name: stg_github_commits
    columns:
      - name: commit_sha
        tests:
          - not_null
          - unique

      - name: repository_id
        tests:
          - not_null

  - name: stg_github_workflow_runs
    columns:
      - name: workflow_run_id
        tests:
          - not_null
          - unique

      - name: status
        tests:
          - not_null