version: 2

models:
  - name: fct_orders
    columns:
      - name: order_key
        tests:
          - not_null
          - unique

      - name: status_code
        tests:
        - accepted_values:
            arguments:
              values: ['O', 'F', 'P']

      - name: item_discount_amount
        tests:
          - not_null